[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "link-args=-lm"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-args=-std=c99 -lm"]

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-C", "link-args=-lm"]

[target.arm-unknown-linux-musleabihf]
rustflags = ["-C", "link-args=-lm"]


